version: "3.7"

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=stackoverflow
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./home/mongodb/
#    command: mongod --smallfiles --logpath=/dev/null

  stackoverflow:
    image: patelravi1291/stackoverflow:v5.2
    environment:
      - MONGO_URI=mongodb://mongodb/stackoverflow
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - mongodb